# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=63, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pic_url', models.URLField(blank=True)),
                ('password', models.CharField(max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='chat.User')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('roll_str', models.CharField(max_length=15)),
                ('results', models.TextField()),
                ('total', models.SmallIntegerField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='roll', serialize=False, to='chat.Message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Game'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='gm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_games', to='chat.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='invitations',
            field=models.ManyToManyField(related_name='invitations', to='chat.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='pc_games', to='chat.User'),
        ),
    ]
