# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-16 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190212_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='message',
        ),
        migrations.DeleteModel(
            name='Roll',
        ),
    ]
