# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190216_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.SlugField(max_length=31, unique=True),
        ),
    ]
